[supabase]
url = "https://lclctovucfvqorqcnglz.supabase.co"
anon_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjbGN0b3Z1Y2Z2cW9ycWNuZ2x6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEzNzcwMjksImV4cCI6MjA4Njk1MzAyOX0.n3O8vMsWCcB8LmDYuC07oY3wsOKavQ838oSU2HY2ChY"
